name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.1.3
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - jupyter=1.1.1
  - pyarrow=14.0.2
  - pip=23.3.1
  - scikit-learn=1.3.2
  - seaborn=0.13.2
  - ydata-profiling=4.10.0
  - ipywidgets=8.1.5
  - nbformat=5.10.4
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
  